<?php

namespace App\Console\Commands;

use Symfony\Component\Process\Process;
use Symfony\Component\Process\Exception\ProcessFailedException;
use Illuminate\Console\Command;

class AuthThemeCommand extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'auth:theme {$git_url}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Download Auth themes for the views generated by artisan make:auth';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
        $git_url = $this->argument('$git_url');
        $warning = 'This will overrite you Auth View Files. Do you wish to continue? [y|N]';
        if ($this->confirm($warning)) {
            $this->info('Getting auth theme from github');
            $process = new Process('git clone '. $git_url . ' tmp_auth && rm -rf tmp_auth/.git && rm -f tmp_auth/readme.md && mv tmp_auth/* resources/views/ && rm -rf tmp_auth');
            $process->run();

            // executes after the command finishes
            if (!$process->isSuccessful()) {
                throw new ProcessFailedException($process);
            }

            echo $process->getOutput();
            $this->info('Successfully added auth theme');
        } else {
            $this->info('Alright, we wount touch anything!');
        }
    }
}
